# Generated by Django 4.2 on 2023-04-14 18:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("name", models.CharField(default="Victor", max_length=256)),
                ("reg_no", models.IntegerField(default=100)),
                (
                    "id",
                    models.IntegerField(
                        default=0, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("period_1", models.BooleanField(default=False)),
                ("period_2", models.BooleanField(default=False)),
                ("period_3", models.BooleanField(default=False)),
                ("period_4", models.BooleanField(default=False)),
                ("period_5", models.BooleanField(default=False)),
                ("period_6", models.BooleanField(default=False)),
                ("period_7", models.BooleanField(default=False)),
                ("log_date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="Date",
            fields=[
                (
                    "date_id",
                    models.IntegerField(default=1, primary_key=True, serialize=False),
                ),
                ("date", models.DateField(max_length=255)),
                ("attendance", models.ManyToManyField(to="Attendance.attendance")),
            ],
        ),
    ]
