# Generated by Django 4.2 on 2023-04-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="date_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
