# Generated by Django 4.2 on 2023-04-16 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="date",
            name="attendance",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="log_date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Attendance.date"
            ),
        ),
        migrations.AlterField(
            model_name="date",
            name="date",
            field=models.DateField(default=django.utils.timezone.now, max_length=255),
        ),
    ]
