# Generated by Django 4.2 on 2023-04-16 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "Attendance",
            "0002_remove_date_attendance_alter_attendance_log_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="log_date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="Attendance.date",
            ),
        ),
    ]
