# Generated by Django 4.2 on 2023-04-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0003_alter_attendance_log_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
