# Generated by Django 4.2 on 2023-04-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Attendance", "0004_alter_attendance_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="date",
            name="date_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
